name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm_flag:
          - "-XX:+UseG1GC" 
          - "-XX:+PrintGCDetails"      
          - "-XX:+OptimizeStringConcat"
          - "-XX:+UseStringDeduplication" 
          - "-XX:+AlwaysPreTouch"    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Log JVM Flag
        run: |
          echo "Running with JVM flag: ${{ matrix.jvm_flag }}"
      
      - name: Build and Test with Maven using JVM Flag
        env:
          MAVEN_OPTS: "${{ matrix.jvm_flag }}"
        timeout-minutes: 15
        run: ./mvnw -B verify

      - name: Log Coverage for Flag
        run: |
           echo "Coverage with flag ${{ matrix.jvm_flag }}: $COVERAGE%"

      - name: Get JaCoCo Coverage
        id: coverage  
        run: |
          coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
          echo "COVERAGE=$coverage" >> $GITHUB_ENV

      - name: Fail if coverage has not improved
        run: |
          coverage=$COVERAGE
          threshold=24.46
          if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
            echo "Coverage is not improved."
            exit 1
          else
            echo "New coverage: $coverage%. Coverage is improved!"
          fi
